name: Auto Sync to ResearchWeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Sync Request
        run: |
          curl -k -X POST https://researchweb.iiit.ac.in/~gopal.kataria/cgi-bin/git-sync.py 
